import { Image, StyleSheet, View } from 'react-native';

import { useColorScheme } from '@/hooks/use-color-scheme';

/**
 * A whisper of film grain over the whole app.
 *
 * This is the cheapest change that stops a flat digital surface reading as
 * flat. It does two jobs: it gives large plain grounds a texture the eye can
 * settle on, and — the part that actually matters — it dithers the banding
 * that big dark gradients show on OLED, where a smooth ramp between two near
 * blacks turns into visible stripes.
 *
 * Deliberately not Skia. The effect needs one texture tiled at low opacity,
 * which a PNG does with no dependencies; @shopify/react-native-skia would mean
 * a native module and an EAS rebuild before anyone could see whether it looked
 * right. The tile is generated by scripts/make-grain.mjs and checked in.
 *
 * Opacity is per-theme and very low. Grain you can consciously see is too much
 * grain — at these values it is only obvious in the A/B. Dark gets more
 * because it has more banding to hide and a darker ground to lift.
 */
const OPACITY = { light: 0.035, dark: 0.055 } as const;

type Props = {
  /** Override the per-theme default, for a surface that wants more or less. */
  opacity?: number;
};

export function Grain({ opacity }: Props) {
  const scheme = useColorScheme() ?? 'light';

  return (
    <View
      // Never intercepts touches: it covers the entire app, so a single missed
      // `pointerEvents` here would make the whole UI untappable.
      pointerEvents="none"
      style={[StyleSheet.absoluteFill, { opacity: opacity ?? OPACITY[scheme] }]}
      // Purely decorative, and announcing it would be noise in every screen's
      // accessibility tree.
      accessible={false}
      importantForAccessibility="no-hide-descendants"
    >
      <Image
        source={require('@/assets/grain.png')}
        // `repeat` tiles the 128px square rather than stretching it, which is
        // the whole point — a stretched noise tile is just a blurry smudge.
        resizeMode="repeat"
        style={StyleSheet.absoluteFill}
        fadeDuration={0}
      />
    </View>
  );
}
